// <auto-generated />
namespace Chronos.Concrete.Migrations.MigrationB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialBSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialBSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201804180136182_InitialBSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
